const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教务人员管理",
                        "menuJump":"列表",
                        "tableName":"jiaowurenyuan"
                    }
                ],
                "menu":"教务人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"班级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBanji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"申请项目管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXuejiyidong"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"学业状态管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueshengxueye"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"学院管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueyuan"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"留言反馈管理",
			            "menuJump":"列表",
			            "tableName":"liuyan"
			        }
			    ],
			    "menu":"留言反馈管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"学生管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	       ,{
	           "child":[
	               {
	                   "buttons":[
	                       "查看",
	                       "审核",
	                       "删除"
	                   ],
	                   "menu":"学籍异动管理",
	                   "menuJump":"列表",
	                   "tableName":"xuejiyidong"
	               }
	           ],
	           "menu":"学籍异动管理"
	       }
	       ,{
	           "child":[
	               {
	                   "buttons":[
	                       "查看",
	                       "新增",
	                       "修改",
	                       "删除"
	                   ],
	                   "menu":"学生学业管理",
	                   "menuJump":"列表",
	                   "tableName":"xueshengxueye"
	               }
	           ],
	           "menu":"学生学业管理"
	       }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"导入导出"
	                    ],
	                    "menu":"学生管理",
	                    "menuJump":"列表",
	                    "tableName":"yonghu"
	                }
	            ],
	            "menu":"学生管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"教务人员",
	    "tableName":"jiaowurenyuan"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"学籍异动管理",
	                    "menuJump":"列表",
	                    "tableName":"xuejiyidong"
	                }
	            ],
	            "menu":"学籍异动管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"学生学业管理",
	                    "menuJump":"列表",
	                    "tableName":"xueshengxueye"
	                }
	            ],
	            "menu":"学生学业管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除"
			            ],
			            "menu":"留言反馈管理",
			            "menuJump":"列表",
			            "tableName":"liuyan"
			        }
			    ],
			    "menu":"留言反馈管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
